<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="WBL06802"><DocLocation><![CDATA[D:\RSAM_Automation_FrameWork\RSAM_Scripts\RSAM_Login_Suite]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[RSAM_Login_Suite]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<AdditionalInfo>
<AdditionalDataName><![CDATA[Web Services Run Toolkit]]></AdditionalDataName>
<AdditionalDataValue><![CDATA[.NET Framework 2.0 WSE 3.0]]></AdditionalDataValue>
</AdditionalInfo>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[RSAM_Login_Suite]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Type mismatch: 'Load_RSAM_Env_XML_File'<BR>Line (32): &quot;Load_RSAM_Env_XML_File&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:33]]></Time>
<TimeTick>1285250913</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Failed" Source="RSAM_Login_Suite" SourceLine="31" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The environment parameter &quot;RSAM_DataTable_Path&quot; was not found. Confirm that an environment parameter with this name is defined or specify another environment variable.<BR>Line (33): &quot;dtTable = Environment(&quot;RSAM_DataTable_Path&quot;)&amp;&quot;\RSAM_Login_Validation.xls&quot;&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Failed" Source="RSAM_Login_Suite" SourceLine="32" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Server&gt; column does not exist.<BR>Line (35): &quot;strServer = DataTable.Value(&quot;Server&quot;,dtLocalSheet)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Failed" Source="RSAM_Login_Suite" SourceLine="34" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;DBName&gt; column does not exist.<BR>Line (36): &quot;strDBName= DataTable.Value(&quot;DBName&quot;,dtLocalSheet)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Failed" Source="RSAM_Login_Suite" SourceLine="35" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;User&gt; column does not exist.<BR>Line (37): &quot;strUsr = DataTable.Value(&quot;User&quot;,dtLocalSheet)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" status="Failed" Source="RSAM_Login_Suite" SourceLine="36" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Pwd&gt; column does not exist.<BR>Line (38): &quot;strPwd = DataTable.Value(&quot;Pwd&quot;,dtLocalSheet)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="14" status="Failed" Source="RSAM_Login_Suite" SourceLine="37" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;UID_Query&gt; column does not exist.<BR>Line (39): &quot;strUsrQuery = DataTable.Value(&quot;UID_Query&quot;,dtLocalSheet)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="15" status="Failed" Source="RSAM_Login_Suite" SourceLine="38" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Pwd_Query&gt; column does not exist.<BR>Line (40): &quot;strPwdQuery = DataTable.Value(&quot;Pwd_Query&quot;,dtLocalSheet)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="16" status="Failed" Source="RSAM_Login_Suite" SourceLine="39" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;URL&gt; column does not exist.<BR>Line (41): &quot;strURL = DataTable.Value(&quot;URL&quot;,dtLocalSheet)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" status="Failed" Source="RSAM_Login_Suite" SourceLine="40" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The environment parameter &quot;pwd&quot; was not found. Confirm that an environment parameter with this name is defined or specify another environment variable.<BR>Line (47): &quot;strEncryptedPwd = RSAM_Password_Encrypt(Environment(&quot;pwd&quot;))&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="18" status="Failed" Source="RSAM_Login_Suite" SourceLine="46" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Type mismatch: 'Get_Value_From_DB'<BR>Line (48): &quot;strDatabaseUsername = Get_Value_From_DB (strServer,strDBName,strUsr,strPwd,strUsrQuery)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="19" status="Failed" Source="RSAM_Login_Suite" SourceLine="47" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Type mismatch: 'Get_Value_From_DB'<BR>Line (49): &quot;strDatabaseFullPwd = Get_Value_From_DB (strServer,strDBName,strUsr,strPwd,strPwdQuery)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="20" status="Failed" Source="RSAM_Login_Suite" SourceLine="48" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The environment parameter &quot;Username&quot; was not found. Confirm that an environment parameter with this name is defined or specify another environment variable.<BR>Line (50): &quot;iUsrLen = Len(Environment(&quot;Username&quot;))&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:34]]></Time>
<TimeTick>1285250914</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="21" status="Failed" Source="RSAM_Login_Suite" SourceLine="49" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The environment parameter &quot;Username&quot; was not found. Confirm that an environment parameter with this name is defined or specify another environment variable.<BR>Line (53): &quot;blCompUsr = strComp(Environment(&quot;Username&quot;),Mid(strDatabaseUsername,1,iUsrLen),1)&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:35]]></Time>
<TimeTick>1285250915</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" status="Failed" Source="RSAM_Login_Suite" SourceLine="52" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Type mismatch: 'RSAM_Launch'<BR>Line (60): &quot;RSAM_Launch &quot;name:=RSAM Login&quot;,&quot;title:=RSAM Login&quot;,strURL&quot;. ]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:35]]></Time>
<TimeTick>1285250915</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" status="Failed" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[RSAM]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:55]]></Time>
<TimeTick>1285250935</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Message from webpage.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/23/2010 - 19:38:55]]></Time>
<TimeTick>1285250935</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[Message from webpage.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Microsoft Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[9/23/2010 - 19:39:37]]></Time>
<TimeTick>1285250977</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ WinButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/23/2010 - 19:39:37]]></Time>
<TimeTick>1285250977</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" status="Warning" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[[ WinButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ WinButton ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "[ WinButton ]" object's parent "RSAM" (class Browser). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[9/23/2010 - 19:39:37]]></Time>
<TimeTick>1285250977</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[RSAM]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = RSAM Password Encryptor.html<br>openurl = file:///D:/RSAM_Automation_FrameWork/RSAM_Library/RSAM%20Password%20Encryptor.html<br>opentitle = <br>Opened By Testing Tool = 0<br>number of tabs = 1<br>Name = RSAM Password Encryptor<br>Has Toolbar = -1<br>Has Status Bar = -1<br>Has Menu Bar = -1<br>]]></Details>
<Time><![CDATA[9/23/2010 - 19:39:37]]></Time>
<TimeTick>1285250977</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="60" status="Warning" nType="Parent description" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[RSAM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[ErrorMessage]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><dl><b><u>Scenario</u>: </b>ErrorMessage<br><b><u>Defined in</u>: </b>D:\RSAM_Automation_FrameWork\RSAM_Recovery\RSAM_Recovery.qrs<br><b><u>Description</u>: </b><br><b><u>Post-recovery operation</u>: </b>Stop the test run.<br><br><b><u>Activated by trigger</u>:</b><dd><u>Type</u>: Test run error<br><u>The error string</u>: Any error</dd><dt><br><b><u>The current test step details</u>:</b><dd><u>Object</u>: WinButton(text := )<br><u>Method</u>: Click<br><u>Arguments</u>: EMPTY<br><u>Result</u>: Cannot identify the object</dd></dt></dl></div></SPAN>]]></Details>
<Time><![CDATA[9/23/2010 - 19:39:37]]></Time>
<TimeTick>1285250977</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Enter]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><b><u>Generate the keyboard event</u>:</b> Enter</div></SPAN>]]></Details>
<Time><![CDATA[9/23/2010 - 19:39:37]]></Time>
<TimeTick>1285250977</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="62" nType="Keyboard operation" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[Enter]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Stop]]></Obj>
<Details plainTxt="False" ><![CDATA[Stop the test run.]]></Details>
<Time><![CDATA[9/23/2010 - 19:39:37]]></Time>
<TimeTick>1285250977</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="63" nType="Test" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[Stop]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="61" nType="Error" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[ErrorMessage]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="59" status="Warning" nType="Run Error" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[[ WinButton ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[9/23/2010 - 19:39:37]]></Time>
<TimeTick>1285250977</TimeTick>
<NodeArgs eType="General" icon="12" nRep="64" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="57" status="Warning" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[Microsoft Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="28" status="Warning" Source="RSAM_Login_Suite" SourceLine="59" >
<Disp><![CDATA[RSAM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/23/2010 - 19:38:33" eTime="9/23/2010 - 19:39:37" passed="0" failed="15" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[RSAM_Login_Suite Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[RSAM_Login_Suite Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="9/23/2010 - 19:38:31" eTime="9/23/2010 - 19:39:37" passed="0" failed="15" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test RSAM_Login_Suite Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>