<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="WBL06802"><DocLocation><![CDATA[D:\RSAM_Automation_FrameWork\RSAM_Scripts\RSAM_Control_Suite]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[RSAM_Control_Suite]]></DName>
<Res><![CDATA[Res20]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<AdditionalInfo>
<AdditionalDataName><![CDATA[Web Services Run Toolkit]]></AdditionalDataName>
<AdditionalDataValue><![CDATA[.NET Framework 2.0 WSE 3.0]]></AdditionalDataValue>
</AdditionalInfo>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[RSAM_Add_Control]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ WebTable ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:26]]></Time>
<TimeTick>1285768226</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="183" >
<Disp><![CDATA[[ WebTable ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA["[  Home  ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:31]]></Time>
<TimeTick>1285768231</TimeTick>
<NodeArgs eType="General" icon="5" nRep="14" >
<Disp><![CDATA["[  Home  ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[  Home  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:32]]></Time>
<TimeTick>1285768232</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="218" >
<Disp><![CDATA[[  Home  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[RSAM]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:34]]></Time>
<TimeTick>1285768234</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[RSAM Home]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:34]]></Time>
<TimeTick>1285768234</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[  Home  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:34]]></Time>
<TimeTick>1285768234</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="20" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="183" >
<Disp><![CDATA[[  Home  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA["[  Manage  ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:35]]></Time>
<TimeTick>1285768235</TimeTick>
<NodeArgs eType="General" icon="5" nRep="23" >
<Disp><![CDATA["[  Manage  ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[  Manage  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:35]]></Time>
<TimeTick>1285768235</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="25" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="218" >
<Disp><![CDATA[[  Manage  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Users/Groups  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:36]]></Time>
<TimeTick>1285768236</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="27" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="224" >
<Disp><![CDATA[[ Users/Groups  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Permission Assignments  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:37]]></Time>
<TimeTick>1285768237</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="30" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="224" >
<Disp><![CDATA[[ Permission Assignments  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ WebTable ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:39]]></Time>
<TimeTick>1285768239</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="36" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="224" >
<Disp><![CDATA[[ WebTable ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Offline Data Gathering  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:40]]></Time>
<TimeTick>1285768240</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="38" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="224" >
<Disp><![CDATA[[ Offline Data Gathering  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ RSAM Scheduler  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:41]]></Time>
<TimeTick>1285768241</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="41" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="224" >
<Disp><![CDATA[[ RSAM Scheduler  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ UCF Control Allocation  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:42]]></Time>
<TimeTick>1285768242</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="44" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="224" >
<Disp><![CDATA[[ UCF Control Allocation  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Administration  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:43]]></Time>
<TimeTick>1285768243</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="47" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="224" >
<Disp><![CDATA[[ Administration  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["[ Administration  ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:44]]></Time>
<TimeTick>1285768244</TimeTick>
<NodeArgs eType="General" icon="5" nRep="50" >
<Disp><![CDATA["[ Administration  ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Administration ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:44]]></Time>
<TimeTick>1285768244</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="52" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="238" >
<Disp><![CDATA[[ Administration ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="19" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="183" >
<Disp><![CDATA[RSAM Home]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[RSAM Administration]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:46]]></Time>
<TimeTick>1285768246</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Controls.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:46]]></Time>
<TimeTick>1285768246</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" Source="RSAM_Add_Control" SourceLine="47" >
<Disp><![CDATA[Controls.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[ControlsFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:50]]></Time>
<TimeTick>1285768250</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Control Types (questions).Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:50]]></Time>
<TimeTick>1285768250</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="58" Source="RSAM_Add_Control" SourceLine="48" >
<Disp><![CDATA[Control Types (questions).Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="57" Source="RSAM_Add_Control" SourceLine="48" >
<Disp><![CDATA[ControlsFrame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="55" Source="RSAM_Add_Control" SourceLine="47" >
<Disp><![CDATA[RSAM Administration]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="18" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="183" >
<Disp><![CDATA[RSAM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Invalid procedure call or argument<BR>Function file: D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs<BR>Line (92): &quot;	Set file_append = fso.OpenTextFile(File_Name, ForAppending,False)&quot;.]]></Details>
<Time><![CDATA[9/29/2010 - 19:20:50]]></Time>
<TimeTick>1285768250</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="59" status="Failed" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="91" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'file_append'<BR>Function file: D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs<BR>Line (93): &quot;	file_append.Write &quot;&lt;tr onClick=(this.bgColor='Yellow') onMouseover=(this.bgColor='LightBlue') onMouseout=(this.bgColor='#FFFFFF')&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;SlNumber&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;TestCase_ID&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;Step_Description&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;Expected_Result&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;Actual_Result&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;Time&amp;&quot;&lt;/td&gt;&quot;&amp;Result_Val&amp;&quot;&quot;&quot;.]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:07]]></Time>
<TimeTick>1285768267</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="60" status="Failed" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="92" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'file_append'<BR>Function file: D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs<BR>Line (94): &quot;	file_append.Close&quot;.]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:08]]></Time>
<TimeTick>1285768268</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="61" status="Failed" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="93" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[RSAM]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:09]]></Time>
<TimeTick>1285768269</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[RSAM Administration]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:09]]></Time>
<TimeTick>1285768269</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[ControlsFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:09]]></Time>
<TimeTick>1285768269</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA["Add"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=Add<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (65 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=Add<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>html id=xlnkAddCtrlQ<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>class=csLinkButton<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>name=Add<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>href=javascript:__doPostBack('xlnkAddCtrlQ','')<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:09]]></Time>
<TimeTick>1285768269</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="65" Source="RSAM_Add_Control" SourceLine="53" >
<Disp><![CDATA["Add"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA["Edit"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=Edit<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (65 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=Edit<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>html id=xlnkEditCtrlQ<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>class=csLinkButton<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>name=Edit<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>href=javascript:__doPostBack('xlnkEditCtrlQ','')<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:09]]></Time>
<TimeTick>1285768269</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="66" Source="RSAM_Add_Control" SourceLine="54" >
<Disp><![CDATA["Edit"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA["Delete"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=Delete<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (65 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=Delete<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>html id=xlnkDelCtrlType<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>class=csLinkButton<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>name=Delete<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>href=javascript:__doPostBack('xlnkDelCtrlType','')<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:09]]></Time>
<TimeTick>1285768269</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="67" Source="RSAM_Add_Control" SourceLine="55" >
<Disp><![CDATA["Delete"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="64" Source="RSAM_Add_Control" SourceLine="53" >
<Disp><![CDATA[ControlsFrame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="63" Source="RSAM_Add_Control" SourceLine="53" >
<Disp><![CDATA[RSAM Administration]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="62" Source="RSAM_Add_Control" SourceLine="53" >
<Disp><![CDATA[RSAM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Invalid procedure call or argument<BR>Function file: D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs<BR>Line (92): &quot;	Set file_append = fso.OpenTextFile(File_Name, ForAppending,False)&quot;.]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:10]]></Time>
<TimeTick>1285768270</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="68" status="Failed" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="91" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'file_append'<BR>Function file: D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs<BR>Line (93): &quot;	file_append.Write &quot;&lt;tr onClick=(this.bgColor='Yellow') onMouseover=(this.bgColor='LightBlue') onMouseout=(this.bgColor='#FFFFFF')&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;SlNumber&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;TestCase_ID&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;Step_Description&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;Expected_Result&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;Actual_Result&amp;&quot;&lt;/td&gt;&lt;td&gt;&lt;Font Face='Verdana' Size='1'&gt;&quot;&amp;Time&amp;&quot;&lt;/td&gt;&quot;&amp;Result_Val&amp;&quot;&quot;&quot;.]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:11]]></Time>
<TimeTick>1285768271</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" status="Failed" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="92" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Object required: 'file_append'<BR>Function file: D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs<BR>Line (94): &quot;	file_append.Close&quot;.]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:12]]></Time>
<TimeTick>1285768272</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="70" status="Failed" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="93" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[RSAM]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:13]]></Time>
<TimeTick>1285768273</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[RSAM Administration]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:13]]></Time>
<TimeTick>1285768273</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[ControlsFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:13]]></Time>
<TimeTick>1285768273</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA["left"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (19 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Image<br>image type=Plain Image<br>html tag=IMG<br>alt=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (23 objects found)&nbsp;</FONT></u><br>
micclass=Image<br>html tag=IMG<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
alt=<SPAN class=passed> (Used</SPAN>, 19 matches)</SPAN><br>image type=Plain Image<SPAN class=passed> (Used</SPAN>, 19 matches)</SPAN><br>html id=ximgLeftIndent<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>name=Image<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>file name=left.jpeg<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>class=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>width=22<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>height=10<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:13]]></Time>
<TimeTick>1285768273</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="74" Source="RSAM_Add_Control" SourceLine="61" >
<Disp><![CDATA["left"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[left.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:13]]></Time>
<TimeTick>1285768273</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="75" Source="RSAM_Add_Control" SourceLine="61" >
<Disp><![CDATA[left.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["right"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (19 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Image<br>image type=Plain Image<br>html tag=IMG<br>alt=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (23 objects found)&nbsp;</FONT></u><br>
micclass=Image<br>html tag=IMG<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
alt=<SPAN class=passed> (Used</SPAN>, 19 matches)</SPAN><br>image type=Plain Image<SPAN class=passed> (Used</SPAN>, 19 matches)</SPAN><br>html id=ximgRightIndent<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>name=Image<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>file name=right.jpg<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>class=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>width=22<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>height=10<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:13]]></Time>
<TimeTick>1285768273</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="76" Source="RSAM_Add_Control" SourceLine="61" >
<Disp><![CDATA["right"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[right.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:13]]></Time>
<TimeTick>1285768273</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="77" Source="RSAM_Add_Control" SourceLine="61" >
<Disp><![CDATA[right.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="73" Source="RSAM_Add_Control" SourceLine="61" >
<Disp><![CDATA[ControlsFrame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="72" Source="RSAM_Add_Control" SourceLine="61" >
<Disp><![CDATA[RSAM Administration]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="71" Source="RSAM_Add_Control" SourceLine="61" >
<Disp><![CDATA[RSAM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Invalid procedure call or argument<BR>Function file: D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs<BR>Line (92): &quot;	Set file_append = fso.OpenTextFile(File_Name, ForAppending,False)&quot;.]]></Details>
<Time><![CDATA[9/29/2010 - 19:21:14]]></Time>
<TimeTick>1285768274</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="78" status="Failed" Source="D:\RSAM_Automation_FrameWork\RSAM_Library\RSAM_Function_Library.vbs" SourceLine="91" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>